# This is a basic workflow to help you get started with Actions

name: Compile Reports

# Controls when the workflow will run
on: 
  push:
    paths:
      - '.github/workflows/report_compiler.yml'
      - 'm2-presentation-soa-report/SoA.md'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

#       # Runs a single command using the runners shell
#       - name: File check
#         run: ls -a
        
      - name: Pandoc Document Converter
        # https://github.com/maxheld83/pandoc-action
        uses: docker://pandoc/latex:2.9
        with:
          args: "m2-presentation-soa-report/SoA.md --toc -so m2-presentation-soa-report/SoA.pdf"

      # Runs a set of commands using the runners shell
      - name: Commit changes
        run: |
          git config --global user.name 'Pandoc Compiler'
          git config --global user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add out.pdf
          git commit -am "Compiled pdf" && git push || echo "No changes to commit"
